### ISSUE TITLE
IOError: Elements/Solid/test.py

### ISSUE THREAD

**Issue by imirzov** [mkraska/CalculiX-Examples#37]
...examples/mkraska/Elements/Solid/test.py

sh: 1: ng_vol: not found
sh: 1: ng_vol: not found
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "solid-conv.py", line 56, in <module>
    f=open("solid.frd")
IOError: [Errno 2] No such file or directory: 'solid.frd'
solid-plot.py:22: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  pylab.hold(True)
/usr/lib/python2.7/dist-packages/matplotlib/__init__.py:806: MatplotlibDeprecationWarning: axes.hold is deprecated. Please remove it from your matplotlibrc and/or style files.
  mplDeprecation)
/usr/lib/python2.7/dist-packages/matplotlib/rcsetup.py:155: MatplotlibDeprecationWarning: axes.hold is deprecated, will be removed in 3.0
  mplDeprecation)
Traceback (most recent call last):
  File "solid-plot.py", line 24, in <module>
    data = numpy.genfromtxt(elty+".txt")
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1549, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: C3D8I.txt not found.

**Comment by mkraska** [comment]
see #39
